### ISSUE TITLE
Please Release Version: 3.0.5

### ISSUE THREAD

**Issue by cyrus07424** [webjars/js-cookie#7]
Please Release Version: 3.0.5

**Comment by jamesward** [comment]
Can you use the NPM WebJar of this instead? `"org.webjars.npm" % "js-cookie" % "3.0.5"`
The upstream project stopped providing direct downloads of the built artifacts:
https://github.com/js-cookie/js-cookie/discussions/820#discussioncomment-5753239

**Comment by cyrus07424** [comment]
I see. I will use NPM WebJar.
Thank you.
